POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "Belattar@exemple.com",
    "password": "123IMAD@ISI__"
}

###

POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "firstName":"Imad",
    "lastName":"Belattar",
    "email": "Belattar@exemple.com",
    "password": "123IMAD@ISI__"
}
###
GET http://localhost:5000/api/v1/elements/completed
Content-type: application/json

{
    "_id":"65922661a1a1e8696d53be11"
}

